// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID       int32     `json:"user_id"`
	UserUuid     uuid.UUID `json:"user_uuid"`
	UserEmail    string    `json:"user_email"`
	UserFullname string    `json:"user_fullname"`
	UserPassword string    `json:"user_password"`
	// -- age >= 18 && age <= 70 --
	UserAge *int32 `json:"user_age"`
	// -- 1: admintrator, 2: moderator  , 3: member--
	UserStatus int32 `json:"user_status"`
	UserLevel  int32 `json:"user_level"`
	// -- deleted at - soft delete row NULL : not deleted  --
	UserDeletedAt pgtype.Timestamptz `json:"user_deleted_at"`
	UserCreatedAt time.Time          `json:"user_created_at"`
	UserUpdatedAt time.Time          `json:"user_updated_at"`
}
