// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context, search *string) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByUUID(ctx context.Context, userUuid uuid.UUID) (User, error)
	GetUsersCreatedAtAsc(ctx context.Context, arg GetUsersCreatedAtAscParams) ([]User, error)
	GetUsersCreatedAtDesc(ctx context.Context, arg GetUsersCreatedAtDescParams) ([]User, error)
	GetUsersIdAsc(ctx context.Context, arg GetUsersIdAscParams) ([]User, error)
	GetUsersIdDesc(ctx context.Context, arg GetUsersIdDescParams) ([]User, error)
	RestoreUsers(ctx context.Context, userUuid uuid.UUID) (User, error)
	SoftDeleteUserByUUID(ctx context.Context, userUuid uuid.UUID) (User, error)
	TrashUsers(ctx context.Context, userUuid uuid.UUID) (User, error)
	UpdateUserByUUID(ctx context.Context, arg UpdateUserByUUIDParams) (User, error)
}

var _ Querier = (*Queries)(nil)
